site_name: Documentação Rede Vision
site_url: https://vision.ime.usp.br/~rodrigocm
site_description: Página de documentação com informações centralizadas, tutoriais e melhores práticas para usuários do Lab Vision.

repo_url: https://www.github.com/lucasmsobrinho/docs-lab-vision
edit_uri: blob/master/docs/
repo_name: docs-lab-vision

theme:
        name: material
        features:
                - content.action.edit
                - content.code.copy

plugins:
  - glightbox
  - git-committers:
          repository: lucasmsobrinho/docs-lab-vision

nav:
  - Início: index.md
  - Primeiros passos: getting-started.md
  - Regras: rules.md
  - Tutoriais:
    - Instalando e configurando o ambiente de trabalho: tutorials/configuring-workplace.md
    - Acessando e editando código remotamente: tutorials/editing-code.md
    - Executando tarefas em segundo plano: tutorials/running-jobs.md
    - Quais recursos estão disponíveis e quanto estou usando?: tutorials/resources.md
    - Configurando o acesso a GPU: tutorials/using-gpu.md
  - Arquitetura da rede: architecture.md
  - Boas Práticas: best-practices.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

